[package]
name = "descent"
version = "0.1.0"
authors = ["Simon Brown <si@sjbrown.co.uk>"]
edition = "2018"
publish = false

[dependencies]
arrayvec = "0.7"
matrixmultiply = "0.3"
rand = "0.8"
rand_chacha = "0.3"
